### ISSUE TITLE
Watching is unreliable

### ISSUE THREAD

**Issue by chris-morgan** [sunng87/handlebars-iron#10] opened 2015-07-02 02:02 UTC
Quite often (perhaps half the time) `watch()` is missing instances of me saving files. If I save it again, then it normally (but still not quite always) works.

**Comment by sunng87** [comment] 2015-07-02 02:14
@chris-morgan Thanks for reporting, Chris. This issue does exist. I may need some time to investigate because currently I'm working on refactoring handlebars-rust library. Will keep you updated. 

By the way, what editor do you use? Does it write anything in the working directory like vim and emacs?

**Comment by chris-morgan** [comment] 2015-07-02 02:37
I use Vim, but I don’t have swap files turned on, so it shouldn’t be writing anything but the actual file.

**Comment by sunng87** [comment] 2015-10-02 03:19
@chris-morgan I cannot reproduce this issue any more except on emacs (which has a known issue with rsnotify). I will close this for now. Feel free to reopen if it still happens to you .

**Closed as completed by sunng87** 2015-10-02 03:19 UTC
Labels: bug
